/** \file
 *  This C source file was generated by $ANTLR version 3.5.2
 *
 *     -  From the grammar source file : SimpleCWalker.g
 *     -                            On : 2020-12-01 14:59:53
 *     -           for the tree parser : SimpleCWalkerTreeParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "SimpleCWalker.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pSimpleCWalker_##scope##_SCOPE
#define SCOPE_STACK(scope)  pSimpleCWalker_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pSimpleCWalker_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pSimpleCWalker_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO
#undef		SEEK
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger



#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   SimpleCWalkerTokenNames[35+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ARG_DEF",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "CHAR_TYPE",
        (pANTLR3_UINT8) "COND",
        (pANTLR3_UINT8) "DIVI",
        (pANTLR3_UINT8) "ELSE_STAT",
        (pANTLR3_UINT8) "EQ",
        (pANTLR3_UINT8) "EQEQ",
        (pANTLR3_UINT8) "FOR",
        (pANTLR3_UINT8) "FUNC_DECL",
        (pANTLR3_UINT8) "FUNC_DEF",
        (pANTLR3_UINT8) "FUNC_HDR",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "IF_STAT",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "INT_TYPE",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "MULT",
        (pANTLR3_UINT8) "OPGT",
        (pANTLR3_UINT8) "OPLT",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "REST",
        (pANTLR3_UINT8) "VAR_DEF",
        (pANTLR3_UINT8) "VOID_TYPE",
        (pANTLR3_UINT8) "WHI_STAT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'else'",
        (pANTLR3_UINT8) "'if'",
        (pANTLR3_UINT8) "'while'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	program    (pSimpleCWalker ctx);
static 
 void
	declaration    (pSimpleCWalker ctx);
static 
 void
	variable    (pSimpleCWalker ctx);
static 
 void
	declarator    (pSimpleCWalker ctx);
static 
 void
	functionHeader    (pSimpleCWalker ctx);
static 
 void
	formalParameter    (pSimpleCWalker ctx);
static 
 void
	type    (pSimpleCWalker ctx);
static 
 void
	block    (pSimpleCWalker ctx);
static 
 void
	cstat    (pSimpleCWalker ctx);
static 
 void
	forStat    (pSimpleCWalker ctx);
static 
 void
	expr    (pSimpleCWalker ctx);
static 
 void
	atom    (pSimpleCWalker ctx);
static void	SimpleCWalkerFree(pSimpleCWalker ctx);
static void     SimpleCWalkerReset (pSimpleCWalker ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "SimpleCWalker.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new SimpleCWalker parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pSimpleCWalker
SimpleCWalkerNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return SimpleCWalkerNewSSD(instream, NULL);
}

/** \brief Create a new SimpleCWalker parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pSimpleCWalker
SimpleCWalkerNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pSimpleCWalker ctx;	    /* Context structure we will build and return   */

    ctx	= (pSimpleCWalker) ANTLR3_CALLOC(1, sizeof(SimpleCWalker));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in SimpleCWalker.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Install the implementation of our SimpleCWalker interface
     */
    ctx->program	= program;
    ctx->declaration	= declaration;
    ctx->variable	= variable;
    ctx->declarator	= declarator;
    ctx->functionHeader	= functionHeader;
    ctx->formalParameter	= formalParameter;
    ctx->type	= type;
    ctx->block	= block;
    ctx->cstat	= cstat;
    ctx->forStat	= forStat;
    ctx->expr	= expr;
    ctx->atom	= atom;
    ctx->free			= SimpleCWalkerFree;
    ctx->reset			= SimpleCWalkerReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = SimpleCWalkerTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
SimpleCWalkerReset (pSimpleCWalker ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 SimpleCWalkerFree(pSimpleCWalker ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);

    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
tree parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return SimpleCWalkerTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_declaration_in_program66  */
static	ANTLR3_BITWORD FOLLOW_declaration_in_program66_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004006002) };
static  ANTLR3_BITSET_LIST FOLLOW_declaration_in_program66	= { FOLLOW_declaration_in_program66_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_declaration86  */
static	ANTLR3_BITWORD FOLLOW_variable_in_declaration86_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_declaration86	= { FOLLOW_variable_in_declaration86_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FUNC_DECL_in_declaration97  */
static	ANTLR3_BITWORD FOLLOW_FUNC_DECL_in_declaration97_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_FUNC_DECL_in_declaration97	= { FOLLOW_FUNC_DECL_in_declaration97_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_functionHeader_in_declaration99  */
static	ANTLR3_BITWORD FOLLOW_functionHeader_in_declaration99_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_functionHeader_in_declaration99	= { FOLLOW_functionHeader_in_declaration99_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FUNC_DEF_in_declaration111  */
static	ANTLR3_BITWORD FOLLOW_FUNC_DEF_in_declaration111_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_FUNC_DEF_in_declaration111	= { FOLLOW_FUNC_DEF_in_declaration111_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_functionHeader_in_declaration113  */
static	ANTLR3_BITWORD FOLLOW_functionHeader_in_declaration113_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_functionHeader_in_declaration113	= { FOLLOW_functionHeader_in_declaration113_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_declaration115  */
static	ANTLR3_BITWORD FOLLOW_block_in_declaration115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_declaration115	= { FOLLOW_block_in_declaration115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VAR_DEF_in_variable136  */
static	ANTLR3_BITWORD FOLLOW_VAR_DEF_in_variable136_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_VAR_DEF_in_variable136	= { FOLLOW_VAR_DEF_in_variable136_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_type_in_variable138  */
static	ANTLR3_BITWORD FOLLOW_type_in_variable138_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_type_in_variable138	= { FOLLOW_type_in_variable138_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_declarator_in_variable140  */
static	ANTLR3_BITWORD FOLLOW_declarator_in_variable140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_declarator_in_variable140	= { FOLLOW_declarator_in_variable140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_declarator160  */
static	ANTLR3_BITWORD FOLLOW_ID_in_declarator160_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_declarator160	= { FOLLOW_ID_in_declarator160_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FUNC_HDR_in_functionHeader181  */
static	ANTLR3_BITWORD FOLLOW_FUNC_HDR_in_functionHeader181_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_FUNC_HDR_in_functionHeader181	= { FOLLOW_FUNC_HDR_in_functionHeader181_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_type_in_functionHeader183  */
static	ANTLR3_BITWORD FOLLOW_type_in_functionHeader183_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_type_in_functionHeader183	= { FOLLOW_type_in_functionHeader183_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_functionHeader185  */
static	ANTLR3_BITWORD FOLLOW_ID_in_functionHeader185_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_functionHeader185	= { FOLLOW_ID_in_functionHeader185_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_formalParameter_in_functionHeader187  */
static	ANTLR3_BITWORD FOLLOW_formalParameter_in_functionHeader187_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000018) };
static  ANTLR3_BITSET_LIST FOLLOW_formalParameter_in_functionHeader187	= { FOLLOW_formalParameter_in_functionHeader187_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ARG_DEF_in_formalParameter209  */
static	ANTLR3_BITWORD FOLLOW_ARG_DEF_in_formalParameter209_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_ARG_DEF_in_formalParameter209	= { FOLLOW_ARG_DEF_in_formalParameter209_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_type_in_formalParameter211  */
static	ANTLR3_BITWORD FOLLOW_type_in_formalParameter211_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_type_in_formalParameter211	= { FOLLOW_type_in_formalParameter211_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_declarator_in_formalParameter213  */
static	ANTLR3_BITWORD FOLLOW_declarator_in_formalParameter213_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_declarator_in_formalParameter213	= { FOLLOW_declarator_in_formalParameter213_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_BLOCK_in_block291  */
static	ANTLR3_BITWORD FOLLOW_BLOCK_in_block291_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_BLOCK_in_block291	= { FOLLOW_BLOCK_in_block291_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_variable_in_block293  */
static	ANTLR3_BITWORD FOLLOW_variable_in_block293_bits[]	= { ANTLR3_UINT64_LIT(0x0000000005851C28) };
static  ANTLR3_BITSET_LIST FOLLOW_variable_in_block293	= { FOLLOW_variable_in_block293_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_cstat_in_block296  */
static	ANTLR3_BITWORD FOLLOW_cstat_in_block296_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001851C28) };
static  ANTLR3_BITSET_LIST FOLLOW_cstat_in_block296	= { FOLLOW_cstat_in_block296_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_forStat_in_cstat310  */
static	ANTLR3_BITWORD FOLLOW_forStat_in_cstat310_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_forStat_in_cstat310	= { FOLLOW_forStat_in_cstat310_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_cstat318  */
static	ANTLR3_BITWORD FOLLOW_expr_in_cstat318_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_cstat318	= { FOLLOW_expr_in_cstat318_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_cstat326  */
static	ANTLR3_BITWORD FOLLOW_block_in_cstat326_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_cstat326	= { FOLLOW_block_in_cstat326_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FOR_in_forStat346  */
static	ANTLR3_BITWORD FOLLOW_FOR_in_forStat346_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_FOR_in_forStat346	= { FOLLOW_FOR_in_forStat346_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_forStat348  */
static	ANTLR3_BITWORD FOLLOW_expr_in_forStat348_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001850C00) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_forStat348	= { FOLLOW_expr_in_forStat348_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_forStat350  */
static	ANTLR3_BITWORD FOLLOW_expr_in_forStat350_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001850C00) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_forStat350	= { FOLLOW_expr_in_forStat350_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_forStat352  */
static	ANTLR3_BITWORD FOLLOW_expr_in_forStat352_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_forStat352	= { FOLLOW_expr_in_forStat352_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_forStat354  */
static	ANTLR3_BITWORD FOLLOW_block_in_forStat354_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_forStat354	= { FOLLOW_block_in_forStat354_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EQEQ_in_expr370  */
static	ANTLR3_BITWORD FOLLOW_EQEQ_in_expr370_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_EQEQ_in_expr370	= { FOLLOW_EQEQ_in_expr370_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr372  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr372_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001850C00) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr372	= { FOLLOW_expr_in_expr372_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr374  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr374_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr374	= { FOLLOW_expr_in_expr374_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OPLT_in_expr386  */
static	ANTLR3_BITWORD FOLLOW_OPLT_in_expr386_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_OPLT_in_expr386	= { FOLLOW_OPLT_in_expr386_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr388  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr388_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001850C00) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr388	= { FOLLOW_expr_in_expr388_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr390  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr390_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr390	= { FOLLOW_expr_in_expr390_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr402  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr402_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr402	= { FOLLOW_PLUS_in_expr402_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr404  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr404_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001850C00) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr404	= { FOLLOW_expr_in_expr404_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr406  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr406_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr406	= { FOLLOW_expr_in_expr406_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EQ_in_expr418  */
static	ANTLR3_BITWORD FOLLOW_EQ_in_expr418_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_EQ_in_expr418	= { FOLLOW_EQ_in_expr418_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_expr420  */
static	ANTLR3_BITWORD FOLLOW_ID_in_expr420_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001850C00) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_expr420	= { FOLLOW_ID_in_expr420_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr422  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr422_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr422	= { FOLLOW_expr_in_expr422_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_expr433  */
static	ANTLR3_BITWORD FOLLOW_atom_in_expr433_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_expr433	= { FOLLOW_atom_in_expr433_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start program
 * SimpleCWalker.g:8:1: program : ( declaration )+ ;
 */
static void
program(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:9:5: ( ( declaration )+ )
        // SimpleCWalker.g:9:9: ( declaration )+
        {
            // SimpleCWalker.g:9:9: ( declaration )+
            {
                int cnt1=0;

                for (;;)
                {
                    int alt1=2;
            	switch ( LA(1) )
            	{
            	case FUNC_DECL:
            	case FUNC_DEF:
            	case VAR_DEF:
            		{
            			alt1=1;
            		}
            	    break;

            	}

            	switch (alt1)
            	{
            	    case 1:
            	        // SimpleCWalker.g:9:9: declaration
            	        {
            	            FOLLOWPUSH(FOLLOW_declaration_in_program66);
            	            declaration(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto ruleprogramEx;
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt1 >= 1 )
            		{
            		    goto loop1;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto ruleprogramEx;
            	}
            	cnt1++;
                }
                loop1: ;	/* Jump to here if this rule does not match */
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end program */

/**
 * $ANTLR start declaration
 * SimpleCWalker.g:12:1: declaration : ( variable | ^( FUNC_DECL functionHeader ) | ^( FUNC_DEF functionHeader block ) );
 */
static void
declaration(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  SimpleCWalker.g:13:5: ( variable | ^( FUNC_DECL functionHeader ) | ^( FUNC_DEF functionHeader block ) )

            ANTLR3_UINT32 alt2;

            alt2=3;

            switch ( LA(1) )
            {
            case VAR_DEF:
            	{
            		alt2=1;
            	}
                break;
            case FUNC_DECL:
            	{
            		alt2=2;
            	}
                break;
            case FUNC_DEF:
            	{
            		alt2=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto ruledeclarationEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // SimpleCWalker.g:13:9: variable
        	    {
        	        FOLLOWPUSH(FOLLOW_variable_in_declaration86);
        	        variable(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // SimpleCWalker.g:14:9: ^( FUNC_DECL functionHeader )
        	    {
        	         MATCHT(FUNC_DECL, &FOLLOW_FUNC_DECL_in_declaration97);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_functionHeader_in_declaration99);
        	        functionHeader(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }



        	    }
        	    break;
        	case 3:
        	    // SimpleCWalker.g:15:9: ^( FUNC_DEF functionHeader block )
        	    {
        	         MATCHT(FUNC_DEF, &FOLLOW_FUNC_DEF_in_declaration111);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_functionHeader_in_declaration113);
        	        functionHeader(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_block_in_declaration115);
        	        block(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclarationEx;
        	        }



        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruledeclarationEx; /* Prevent compiler warnings */
    ruledeclarationEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end declaration */

/**
 * $ANTLR start variable
 * SimpleCWalker.g:18:1: variable : ^( VAR_DEF type declarator ) ;
 */
static void
variable(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:19:5: ( ^( VAR_DEF type declarator ) )
        // SimpleCWalker.g:19:9: ^( VAR_DEF type declarator )
        {
             MATCHT(VAR_DEF, &FOLLOW_VAR_DEF_in_variable136);
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }

            FOLLOWPUSH(FOLLOW_type_in_variable138);
            type(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }


            FOLLOWPUSH(FOLLOW_declarator_in_variable140);
            declarator(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto rulevariableEx;
            }



        }

    }

    // This is where rules clean up and exit
    //
    goto rulevariableEx; /* Prevent compiler warnings */
    rulevariableEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end variable */

/**
 * $ANTLR start declarator
 * SimpleCWalker.g:22:1: declarator : ID ;
 */
static void
declarator(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:23:5: ( ID )
        // SimpleCWalker.g:23:9: ID
        {
             MATCHT(ID, &FOLLOW_ID_in_declarator160);
            if  (HASEXCEPTION())
            {
                goto ruledeclaratorEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruledeclaratorEx; /* Prevent compiler warnings */
    ruledeclaratorEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end declarator */

/**
 * $ANTLR start functionHeader
 * SimpleCWalker.g:26:1: functionHeader : ^( FUNC_HDR type ID ( formalParameter )+ ) ;
 */
static void
functionHeader(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:27:5: ( ^( FUNC_HDR type ID ( formalParameter )+ ) )
        // SimpleCWalker.g:27:9: ^( FUNC_HDR type ID ( formalParameter )+ )
        {
             MATCHT(FUNC_HDR, &FOLLOW_FUNC_HDR_in_functionHeader181);
            if  (HASEXCEPTION())
            {
                goto rulefunctionHeaderEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto rulefunctionHeaderEx;
            }

            FOLLOWPUSH(FOLLOW_type_in_functionHeader183);
            type(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulefunctionHeaderEx;
            }


             MATCHT(ID, &FOLLOW_ID_in_functionHeader185);
            if  (HASEXCEPTION())
            {
                goto rulefunctionHeaderEx;
            }


            // SimpleCWalker.g:27:28: ( formalParameter )+
            {
                int cnt3=0;

                for (;;)
                {
                    int alt3=2;
            	switch ( LA(1) )
            	{
            	case ARG_DEF:
            		{
            			alt3=1;
            		}
            	    break;

            	}

            	switch (alt3)
            	{
            	    case 1:
            	        // SimpleCWalker.g:27:28: formalParameter
            	        {
            	            FOLLOWPUSH(FOLLOW_formalParameter_in_functionHeader187);
            	            formalParameter(ctx);

            	            FOLLOWPOP();
            	            if  (HASEXCEPTION())
            	            {
            	                goto rulefunctionHeaderEx;
            	            }


            	        }
            	        break;

            	    default:

            		if ( cnt3 >= 1 )
            		{
            		    goto loop3;
            		}
            		/* mismatchedSetEx()
            		 */
            		CONSTRUCTEX();
            		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
            		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


            		goto rulefunctionHeaderEx;
            	}
            	cnt3++;
                }
                loop3: ;	/* Jump to here if this rule does not match */
            }

            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto rulefunctionHeaderEx;
            }



        }

    }

    // This is where rules clean up and exit
    //
    goto rulefunctionHeaderEx; /* Prevent compiler warnings */
    rulefunctionHeaderEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end functionHeader */

/**
 * $ANTLR start formalParameter
 * SimpleCWalker.g:30:1: formalParameter : ^( ARG_DEF type declarator ) ;
 */
static void
formalParameter(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:31:5: ( ^( ARG_DEF type declarator ) )
        // SimpleCWalker.g:31:9: ^( ARG_DEF type declarator )
        {
             MATCHT(ARG_DEF, &FOLLOW_ARG_DEF_in_formalParameter209);
            if  (HASEXCEPTION())
            {
                goto ruleformalParameterEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleformalParameterEx;
            }

            FOLLOWPUSH(FOLLOW_type_in_formalParameter211);
            type(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleformalParameterEx;
            }


            FOLLOWPUSH(FOLLOW_declarator_in_formalParameter213);
            declarator(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleformalParameterEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleformalParameterEx;
            }



        }

    }

    // This is where rules clean up and exit
    //
    goto ruleformalParameterEx; /* Prevent compiler warnings */
    ruleformalParameterEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end formalParameter */

/**
 * $ANTLR start type
 * SimpleCWalker.g:34:1: type : ( 'int' | 'char' | 'void' | ID );
 */
static void
type(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:35:5: ( 'int' | 'char' | 'void' | ID )
        // SimpleCWalker.g:
        {
            if ( LA(1) == CHAR_TYPE || LA(1) == ID || LA(1) == INT_TYPE || LA(1) == VOID_TYPE )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                goto ruletypeEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruletypeEx; /* Prevent compiler warnings */
    ruletypeEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end type */

/**
 * $ANTLR start block
 * SimpleCWalker.g:41:1: block : ^( BLOCK ( variable )* ( cstat )* ) ;
 */
static void
block(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:42:5: ( ^( BLOCK ( variable )* ( cstat )* ) )
        // SimpleCWalker.g:42:9: ^( BLOCK ( variable )* ( cstat )* )
        {
             MATCHT(BLOCK, &FOLLOW_BLOCK_in_block291);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }


            if ( LA(1)==ANTLR3_TOKEN_DOWN ) {
                MATCHT(ANTLR3_TOKEN_DOWN, NULL);
                if  (HASEXCEPTION())
                {
                    goto ruleblockEx;
                }

                // SimpleCWalker.g:42:17: ( variable )*

                for (;;)
                {
                    int alt4=2;
                    switch ( LA(1) )
                    {
                    case VAR_DEF:
                    	{
                    		alt4=1;
                    	}
                        break;

                    }

                    switch (alt4)
                    {
                	case 1:
                	    // SimpleCWalker.g:42:17: variable
                	    {
                	        FOLLOWPUSH(FOLLOW_variable_in_block293);
                	        variable(ctx);

                	        FOLLOWPOP();
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleblockEx;
                	        }


                	    }
                	    break;

                	default:
                	    goto loop4;	/* break out of the loop */
                	    break;
                    }
                }
                loop4: ; /* Jump out to here if this rule does not match */


                // SimpleCWalker.g:42:27: ( cstat )*

                for (;;)
                {
                    int alt5=2;
                    switch ( LA(1) )
                    {
                    case BLOCK:
                    case EQ:
                    case EQEQ:
                    case FOR:
                    case ID:
                    case INT:
                    case OPLT:
                    case PLUS:
                    	{
                    		alt5=1;
                    	}
                        break;

                    }

                    switch (alt5)
                    {
                	case 1:
                	    // SimpleCWalker.g:42:27: cstat
                	    {
                	        FOLLOWPUSH(FOLLOW_cstat_in_block296);
                	        cstat(ctx);

                	        FOLLOWPOP();
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleblockEx;
                	        }


                	    }
                	    break;

                	default:
                	    goto loop5;	/* break out of the loop */
                	    break;
                    }
                }
                loop5: ; /* Jump out to here if this rule does not match */


                MATCHT(ANTLR3_TOKEN_UP, NULL);
                if  (HASEXCEPTION())
                {
                    goto ruleblockEx;
                }

            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblockEx; /* Prevent compiler warnings */
    ruleblockEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end block */

/**
 * $ANTLR start cstat
 * SimpleCWalker.g:45:1: cstat : ( forStat | expr | block );
 */
static void
cstat(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  SimpleCWalker.g:45:6: ( forStat | expr | block )

            ANTLR3_UINT32 alt6;

            alt6=3;

            switch ( LA(1) )
            {
            case FOR:
            	{
            		alt6=1;
            	}
                break;
            case EQ:
            case EQEQ:
            case ID:
            case INT:
            case OPLT:
            case PLUS:
            	{
            		alt6=2;
            	}
                break;
            case BLOCK:
            	{
            		alt6=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto rulecstatEx;

            }

            switch (alt6)
            {
        	case 1:
        	    // SimpleCWalker.g:45:8: forStat
        	    {
        	        FOLLOWPUSH(FOLLOW_forStat_in_cstat310);
        	        forStat(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecstatEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // SimpleCWalker.g:46:7: expr
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_cstat318);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecstatEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // SimpleCWalker.g:47:7: block
        	    {
        	        FOLLOWPUSH(FOLLOW_block_in_cstat326);
        	        block(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecstatEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulecstatEx; /* Prevent compiler warnings */
    rulecstatEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end cstat */

/**
 * $ANTLR start forStat
 * SimpleCWalker.g:50:1: forStat : ^( 'for' expr expr expr block ) ;
 */
static void
forStat(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:51:5: ( ^( 'for' expr expr expr block ) )
        // SimpleCWalker.g:51:9: ^( 'for' expr expr expr block )
        {
             MATCHT(FOR, &FOLLOW_FOR_in_forStat346);
            if  (HASEXCEPTION())
            {
                goto ruleforStatEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleforStatEx;
            }

            FOLLOWPUSH(FOLLOW_expr_in_forStat348);
            expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleforStatEx;
            }


            FOLLOWPUSH(FOLLOW_expr_in_forStat350);
            expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleforStatEx;
            }


            FOLLOWPUSH(FOLLOW_expr_in_forStat352);
            expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleforStatEx;
            }


            FOLLOWPUSH(FOLLOW_block_in_forStat354);
            block(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleforStatEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleforStatEx;
            }



        }

    }

    // This is where rules clean up and exit
    //
    goto ruleforStatEx; /* Prevent compiler warnings */
    ruleforStatEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end forStat */

/**
 * $ANTLR start expr
 * SimpleCWalker.g:54:1: expr : ( ^( EQEQ expr expr ) | ^( OPLT expr expr ) | ^( PLUS expr expr ) | ^( EQ ID expr ) | atom );
 */
static void
expr(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  SimpleCWalker.g:54:5: ( ^( EQEQ expr expr ) | ^( OPLT expr expr ) | ^( PLUS expr expr ) | ^( EQ ID expr ) | atom )

            ANTLR3_UINT32 alt7;

            alt7=5;

            switch ( LA(1) )
            {
            case EQEQ:
            	{
            		alt7=1;
            	}
                break;
            case OPLT:
            	{
            		alt7=2;
            	}
                break;
            case PLUS:
            	{
            		alt7=3;
            	}
                break;
            case EQ:
            	{
            		alt7=4;
            	}
                break;
            case ID:
            case INT:
            	{
            		alt7=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruleexprEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // SimpleCWalker.g:54:9: ^( EQEQ expr expr )
        	    {
        	         MATCHT(EQEQ, &FOLLOW_EQEQ_in_expr370);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_expr372);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_expr374);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // SimpleCWalker.g:55:9: ^( OPLT expr expr )
        	    {
        	         MATCHT(OPLT, &FOLLOW_OPLT_in_expr386);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_expr388);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_expr390);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }



        	    }
        	    break;
        	case 3:
        	    // SimpleCWalker.g:56:9: ^( PLUS expr expr )
        	    {
        	         MATCHT(PLUS, &FOLLOW_PLUS_in_expr402);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_expr404);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_expr406);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }



        	    }
        	    break;
        	case 4:
        	    // SimpleCWalker.g:57:9: ^( EQ ID expr )
        	    {
        	         MATCHT(EQ, &FOLLOW_EQ_in_expr418);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	         MATCHT(ID, &FOLLOW_ID_in_expr420);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_expr422);
        	        expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }



        	    }
        	    break;
        	case 5:
        	    // SimpleCWalker.g:58:9: atom
        	    {
        	        FOLLOWPUSH(FOLLOW_atom_in_expr433);
        	        atom(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end expr */

/**
 * $ANTLR start atom
 * SimpleCWalker.g:61:1: atom : ( ID | INT );
 */
static void
atom(pSimpleCWalker ctx)
{
    /* Initialize rule variables
     */

    {
        // SimpleCWalker.g:62:5: ( ID | INT )
        // SimpleCWalker.g:
        {
            if ( LA(1) == ID || LA(1) == INT )
            {
                CONSUME();
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                goto ruleatomEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end atom */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
