/** \file
 *  This C source file was generated by $ANTLR version 3.5.2
 *
 *     -  From the grammar source file : SimpleC.g
 *     -                            On : 2021-03-05 18:00:26
 *     -                 for the lexer : SimpleCLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#define _empty NULL

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "SimpleCLexer.h"
/* ----------------------------------------- */


/** String literals used by SimpleCLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x63, 0x68, 0x61, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x65, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x69, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x72, 0x65, 0x74, 0x75, 0x72, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x77, 0x68, 0x69, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x76, 0x6F, 0x69, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x21, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x3C, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x3E, 0x3D,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pSimpleCLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pSimpleCLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pSimpleCLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pSimpleCLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__39    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__40    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__41    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__42    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__43    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__44    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__45    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__46    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__47    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__48    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__49    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__50    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mT__51    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mFOR    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mVOID_TYPE    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mCHARACTER_LITERAL    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_LITERAL    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mEscapeSequence    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mEQ    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mEQEQ    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mNEQ    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mOPLT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mLTEQ    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mOPGT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mGTEQ    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mPLUS    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mMINUS    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mDIVI    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mREST    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mMULT    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pSimpleCLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pSimpleCLexer ctx);
static void	SimpleCLexerFree(pSimpleCLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
SimpleCLexerFree  (pSimpleCLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
SimpleCLexerReset (pSimpleCLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "SimpleC.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called SimpleCLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pSimpleCLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSimpleCLexer SimpleCLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return SimpleCLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called SimpleCLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pSimpleCLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSimpleCLexer SimpleCLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pSimpleCLexer ctx; // Context structure we will build and return

    ctx = (pSimpleCLexer) ANTLR3_CALLOC(1, sizeof(SimpleCLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in SimpleCLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our SimpleCLexer interface
     */
    ctx->mT__39	= mT__39;
    ctx->mT__40	= mT__40;
    ctx->mT__41	= mT__41;
    ctx->mT__42	= mT__42;
    ctx->mT__43	= mT__43;
    ctx->mT__44	= mT__44;
    ctx->mT__45	= mT__45;
    ctx->mT__46	= mT__46;
    ctx->mT__47	= mT__47;
    ctx->mT__48	= mT__48;
    ctx->mT__49	= mT__49;
    ctx->mT__50	= mT__50;
    ctx->mT__51	= mT__51;
    ctx->mFOR	= mFOR;
    ctx->mVOID_TYPE	= mVOID_TYPE;
    ctx->mID	= mID;
    ctx->mINT	= mINT;
    ctx->mCHARACTER_LITERAL	= mCHARACTER_LITERAL;
    ctx->mSTRING_LITERAL	= mSTRING_LITERAL;
    ctx->mEscapeSequence	= mEscapeSequence;
    ctx->mEQ	= mEQ;
    ctx->mEQEQ	= mEQEQ;
    ctx->mNEQ	= mNEQ;
    ctx->mOPLT	= mOPLT;
    ctx->mLTEQ	= mLTEQ;
    ctx->mOPGT	= mOPGT;
    ctx->mGTEQ	= mGTEQ;
    ctx->mPLUS	= mPLUS;
    ctx->mMINUS	= mMINUS;
    ctx->mDIVI	= mDIVI;
    ctx->mREST	= mREST;
    ctx->mMULT	= mMULT;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= SimpleCLexerFree;
    ctx->reset          = SimpleCLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 11:7: ( '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__39
 *
 * Looks to match the characters the constitute the token T__39
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__39(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__39;


    // SimpleC.g:11:7: ( '&' )
    // SimpleC.g:11:9: '&'
    {
        MATCHC('&');
        if  (HASEXCEPTION())
        {
            goto ruleT__39Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__39Ex; /* Prevent compiler warnings */
    ruleT__39Ex: ;

}
// $ANTLR end T__39

//   Comes from: 12:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;


    // SimpleC.g:12:7: ( '(' )
    // SimpleC.g:12:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 13:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__41;


    // SimpleC.g:13:7: ( ')' )
    // SimpleC.g:13:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 14:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__42(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__42;


    // SimpleC.g:14:7: ( ',' )
    // SimpleC.g:14:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleT__42Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 15:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__43
 *
 * Looks to match the characters the constitute the token T__43
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__43(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__43;


    // SimpleC.g:15:7: ( ';' )
    // SimpleC.g:15:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleT__43Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__43Ex; /* Prevent compiler warnings */
    ruleT__43Ex: ;

}
// $ANTLR end T__43

//   Comes from: 16:7: ( 'char' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__44
 *
 * Looks to match the characters the constitute the token T__44
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__44(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__44;


    // SimpleC.g:16:7: ( 'char' )
    // SimpleC.g:16:9: 'char'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__44Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__44Ex; /* Prevent compiler warnings */
    ruleT__44Ex: ;

}
// $ANTLR end T__44

//   Comes from: 17:7: ( 'else' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__45
 *
 * Looks to match the characters the constitute the token T__45
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__45(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__45;


    // SimpleC.g:17:7: ( 'else' )
    // SimpleC.g:17:9: 'else'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__45Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__45Ex; /* Prevent compiler warnings */
    ruleT__45Ex: ;

}
// $ANTLR end T__45

//   Comes from: 18:7: ( 'if' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__46
 *
 * Looks to match the characters the constitute the token T__46
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__46(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__46;


    // SimpleC.g:18:7: ( 'if' )
    // SimpleC.g:18:9: 'if'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleT__46Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__46Ex; /* Prevent compiler warnings */
    ruleT__46Ex: ;

}
// $ANTLR end T__46

//   Comes from: 19:7: ( 'int' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__47
 *
 * Looks to match the characters the constitute the token T__47
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__47(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__47;


    // SimpleC.g:19:7: ( 'int' )
    // SimpleC.g:19:9: 'int'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleT__47Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__47Ex; /* Prevent compiler warnings */
    ruleT__47Ex: ;

}
// $ANTLR end T__47

//   Comes from: 20:7: ( 'return' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__48
 *
 * Looks to match the characters the constitute the token T__48
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__48(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__48;


    // SimpleC.g:20:7: ( 'return' )
    // SimpleC.g:20:9: 'return'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleT__48Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__48Ex; /* Prevent compiler warnings */
    ruleT__48Ex: ;

}
// $ANTLR end T__48

//   Comes from: 21:7: ( 'while' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__49
 *
 * Looks to match the characters the constitute the token T__49
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__49(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__49;


    // SimpleC.g:21:7: ( 'while' )
    // SimpleC.g:21:9: 'while'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleT__49Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__49Ex; /* Prevent compiler warnings */
    ruleT__49Ex: ;

}
// $ANTLR end T__49

//   Comes from: 22:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__50
 *
 * Looks to match the characters the constitute the token T__50
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__50(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__50;


    // SimpleC.g:22:7: ( '{' )
    // SimpleC.g:22:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleT__50Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__50Ex; /* Prevent compiler warnings */
    ruleT__50Ex: ;

}
// $ANTLR end T__50

//   Comes from: 23:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__51
 *
 * Looks to match the characters the constitute the token T__51
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__51(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__51;


    // SimpleC.g:23:7: ( '}' )
    // SimpleC.g:23:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleT__51Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__51Ex; /* Prevent compiler warnings */
    ruleT__51Ex: ;

}
// $ANTLR end T__51

//   Comes from: 168:5: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FOR
 *
 * Looks to match the characters the constitute the token FOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFOR(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FOR;


    // SimpleC.g:168:5: ( 'for' )
    // SimpleC.g:168:7: 'for'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleFOREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFOREx; /* Prevent compiler warnings */
    ruleFOREx: ;

}
// $ANTLR end FOR

//   Comes from: 170:10: ( 'void' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VOID_TYPE
 *
 * Looks to match the characters the constitute the token VOID_TYPE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mVOID_TYPE(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = VOID_TYPE;


    // SimpleC.g:170:10: ( 'void' )
    // SimpleC.g:170:12: 'void'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleVOID_TYPEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleVOID_TYPEEx; /* Prevent compiler warnings */
    ruleVOID_TYPEEx: ;

}
// $ANTLR end VOID_TYPE

//   Comes from: 174:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // SimpleC.g:174:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // SimpleC.g:174:9: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            LRECOVER();
            goto ruleIDEx;
        }


        // SimpleC.g:174:33: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1)
            {
        	case 1:
        	    // SimpleC.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	            LRECOVER();
        	            goto ruleIDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 177:5: ( ( '0' | '1' .. '9' ( '0' .. '9' )* ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // SimpleC.g:177:5: ( ( '0' | '1' .. '9' ( '0' .. '9' )* ) )
    // SimpleC.g:177:7: ( '0' | '1' .. '9' ( '0' .. '9' )* )
    {
        // SimpleC.g:177:7: ( '0' | '1' .. '9' ( '0' .. '9' )* )
        {
            int alt3=2;
            switch ( LA(1) )
            {
            case '0':
            	{
            		alt3=1;
            	}
                break;
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleINTEx;

            }

            switch (alt3)
            {
        	case 1:
        	    // SimpleC.g:177:8: '0'
        	    {
        	        MATCHC('0');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // SimpleC.g:177:14: '1' .. '9' ( '0' .. '9' )*
        	    {
        	        MATCHRANGE('1', '9');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEx;
        	        }


        	        // SimpleC.g:177:23: ( '0' .. '9' )*

        	        for (;;)
        	        {
        	            int alt2=2;
        	            switch ( LA(1) )
        	            {
        	            case '0':
        	            case '1':
        	            case '2':
        	            case '3':
        	            case '4':
        	            case '5':
        	            case '6':
        	            case '7':
        	            case '8':
        	            case '9':
        	            	{
        	            		alt2=1;
        	            	}
        	                break;

        	            }

        	            switch (alt2)
        	            {
        	        	case 1:
        	        	    // SimpleC.g:
        	        	    {
        	        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        	        {
        	        	            CONSUME();
        	        	        }
        	        	        else
        	        	        {
        	        	            CONSTRUCTEX();
        	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	        	            LRECOVER();
        	        	            goto ruleINTEx;
        	        	        }


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop2;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop2: ; /* Jump out to here if this rule does not match */


        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 181:5: ( '\\'' ( EscapeSequence |~ ( '\\'' | '\\\\' ) ) '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHARACTER_LITERAL
 *
 * Looks to match the characters the constitute the token CHARACTER_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHARACTER_LITERAL(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHARACTER_LITERAL;


    // SimpleC.g:181:5: ( '\\'' ( EscapeSequence |~ ( '\\'' | '\\\\' ) ) '\\'' )
    // SimpleC.g:181:9: '\\'' ( EscapeSequence |~ ( '\\'' | '\\\\' ) ) '\\''
    {
        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


        // SimpleC.g:181:14: ( EscapeSequence |~ ( '\\'' | '\\\\' ) )
        {
            int alt4=2;
            {
                int LA4_0 = LA(1);
                if ( (LA4_0 == '\\'))
                {
                    alt4=1;
                }
                else if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '&')) || ((LA4_0 >= '(') && (LA4_0 <= '[')) || ((LA4_0 >= ']') && (LA4_0 <= 0xFFFF))))
                {
                    alt4=2;
                }
                else
                {

                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 4;
                    EXCEPTION->state        = 0;


                    goto ruleCHARACTER_LITERALEx;

                }
            }
            switch (alt4)
            {
        	case 1:
        	    // SimpleC.g:181:16: EscapeSequence
        	    {
        	        /* 181:16: EscapeSequence */
        	        mEscapeSequence(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCHARACTER_LITERALEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // SimpleC.g:181:33: ~ ( '\\'' | '\\\\' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	            LRECOVER();
        	            goto ruleCHARACTER_LITERALEx;
        	        }


        	    }
        	    break;

            }
        }

        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHARACTER_LITERALEx; /* Prevent compiler warnings */
    ruleCHARACTER_LITERALEx: ;

}
// $ANTLR end CHARACTER_LITERAL

//   Comes from: 184:5: ( '\"' ( EscapeSequence |~ ( '\\\\' | '\"' ) )* '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_LITERAL
 *
 * Looks to match the characters the constitute the token STRING_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_LITERAL(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING_LITERAL;


    // SimpleC.g:184:5: ( '\"' ( EscapeSequence |~ ( '\\\\' | '\"' ) )* '\"' )
    // SimpleC.g:184:8: '\"' ( EscapeSequence |~ ( '\\\\' | '\"' ) )* '\"'
    {
        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


        // SimpleC.g:184:12: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*

        for (;;)
        {
            int alt5=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA5_0 = LA(1);
                if ( (LA5_0 == '\\'))
                {
                    alt5=1;
                }
                else if ( (((LA5_0 >= 0x0000) && (LA5_0 <= '!')) || ((LA5_0 >= '#') && (LA5_0 <= '[')) || ((LA5_0 >= ']') && (LA5_0 <= 0xFFFF))))
                {
                    alt5=2;
                }

            }
            switch (alt5)
            {
        	case 1:
        	    // SimpleC.g:184:14: EscapeSequence
        	    {
        	        /* 184:14: EscapeSequence */
        	        mEscapeSequence(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_LITERALEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // SimpleC.g:184:31: ~ ( '\\\\' | '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	            LRECOVER();
        	            goto ruleSTRING_LITERALEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop5;	/* break out of the loop */
        	    break;
            }
        }
        loop5: ; /* Jump out to here if this rule does not match */


        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRING_LITERALEx; /* Prevent compiler warnings */
    ruleSTRING_LITERALEx: ;

}
// $ANTLR end STRING_LITERAL

//   Comes from: 190:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EscapeSequence
 *
 * Looks to match the characters the constitute the token EscapeSequence
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEscapeSequence(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;


    // SimpleC.g:190:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
    // SimpleC.g:190:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
    {
        MATCHC('\\');
        if  (HASEXCEPTION())
        {
            goto ruleEscapeSequenceEx;
        }


        if ( LA(1) == '"' || LA(1) == '\'' || LA(1) == '\\' || LA(1) == 'b' || LA(1) == 'f' || LA(1) == 'n' || LA(1) == 'r' || LA(1) == 't' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            LRECOVER();
            goto ruleEscapeSequenceEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleEscapeSequenceEx; /* Prevent compiler warnings */
    ruleEscapeSequenceEx: ;

}
// $ANTLR end EscapeSequence

//   Comes from: 192:6: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQ
 *
 * Looks to match the characters the constitute the token EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQ(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQ;


    // SimpleC.g:192:6: ( '=' )
    // SimpleC.g:192:8: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleEQEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQEx; /* Prevent compiler warnings */
    ruleEQEx: ;

}
// $ANTLR end EQ

//   Comes from: 193:6: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQEQ
 *
 * Looks to match the characters the constitute the token EQEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQEQ(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQEQ;


    // SimpleC.g:193:6: ( '==' )
    // SimpleC.g:193:8: '=='
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleEQEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQEQEx; /* Prevent compiler warnings */
    ruleEQEQEx: ;

}
// $ANTLR end EQEQ

//   Comes from: 194:5: ( '!=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NEQ
 *
 * Looks to match the characters the constitute the token NEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNEQ(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NEQ;


    // SimpleC.g:194:5: ( '!=' )
    // SimpleC.g:194:7: '!='
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleNEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEQEx; /* Prevent compiler warnings */
    ruleNEQEx: ;

}
// $ANTLR end NEQ

//   Comes from: 195:8: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPLT
 *
 * Looks to match the characters the constitute the token OPLT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPLT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPLT;


    // SimpleC.g:195:8: ( '<' )
    // SimpleC.g:195:10: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleOPLTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPLTEx; /* Prevent compiler warnings */
    ruleOPLTEx: ;

}
// $ANTLR end OPLT

//   Comes from: 196:8: ( '<=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LTEQ
 *
 * Looks to match the characters the constitute the token LTEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLTEQ(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LTEQ;


    // SimpleC.g:196:8: ( '<=' )
    // SimpleC.g:196:10: '<='
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleLTEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLTEQEx; /* Prevent compiler warnings */
    ruleLTEQEx: ;

}
// $ANTLR end LTEQ

//   Comes from: 197:6: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPGT
 *
 * Looks to match the characters the constitute the token OPGT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPGT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPGT;


    // SimpleC.g:197:6: ( '>' )
    // SimpleC.g:197:8: '>'
    {
        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleOPGTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPGTEx; /* Prevent compiler warnings */
    ruleOPGTEx: ;

}
// $ANTLR end OPGT

//   Comes from: 198:5: ( '>=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start GTEQ
 *
 * Looks to match the characters the constitute the token GTEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mGTEQ(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = GTEQ;


    // SimpleC.g:198:5: ( '>=' )
    // SimpleC.g:198:7: '>='
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleGTEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleGTEQEx; /* Prevent compiler warnings */
    ruleGTEQEx: ;

}
// $ANTLR end GTEQ

//   Comes from: 199:6: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;


    // SimpleC.g:199:6: ( '+' )
    // SimpleC.g:199:8: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 200:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MINUS
 *
 * Looks to match the characters the constitute the token MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMINUS(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MINUS;


    // SimpleC.g:200:7: ( '-' )
    // SimpleC.g:200:9: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleMINUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMINUSEx; /* Prevent compiler warnings */
    ruleMINUSEx: ;

}
// $ANTLR end MINUS

//   Comes from: 201:6: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIVI
 *
 * Looks to match the characters the constitute the token DIVI
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIVI(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DIVI;


    // SimpleC.g:201:6: ( '/' )
    // SimpleC.g:201:8: '/'
    {
        MATCHC('/');
        if  (HASEXCEPTION())
        {
            goto ruleDIVIEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDIVIEx; /* Prevent compiler warnings */
    ruleDIVIEx: ;

}
// $ANTLR end DIVI

//   Comes from: 202:6: ( '%' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start REST
 *
 * Looks to match the characters the constitute the token REST
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mREST(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = REST;


    // SimpleC.g:202:6: ( '%' )
    // SimpleC.g:202:8: '%'
    {
        MATCHC('%');
        if  (HASEXCEPTION())
        {
            goto ruleRESTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRESTEx; /* Prevent compiler warnings */
    ruleRESTEx: ;

}
// $ANTLR end REST

//   Comes from: 203:6: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MULT
 *
 * Looks to match the characters the constitute the token MULT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMULT(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MULT;


    // SimpleC.g:203:6: ( '*' )
    // SimpleC.g:203:8: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleMULTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMULTEx; /* Prevent compiler warnings */
    ruleMULTEx: ;

}
// $ANTLR end MULT

//   Comes from: 206:5: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pSimpleCLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // SimpleC.g:206:5: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
    // SimpleC.g:206:9: ( ' ' | '\\t' | '\\r' | '\\n' )+
    {
        // SimpleC.g:206:9: ( ' ' | '\\t' | '\\r' | '\\n' )+
        {
            int cnt6=0;

            for (;;)
            {
                int alt6=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt6=1;
        		}
        	    break;

        	}

        	switch (alt6)
        	{
        	    case 1:
        	        // SimpleC.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt6 >= 1 )
        		{
        		    goto loop6;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt6++;
            }
            loop6: ;	/* Jump to here if this rule does not match */
        }

        {
             LEXSTATE->channel=HIDDEN; 
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pSimpleCLexer ctx)
{
    {
        //  SimpleC.g:1:8: ( T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | FOR | VOID_TYPE | ID | INT | CHARACTER_LITERAL | STRING_LITERAL | EQ | EQEQ | NEQ | OPLT | LTEQ | OPGT | GTEQ | PLUS | MINUS | DIVI | REST | MULT | WS )

        ANTLR3_UINT32 alt7;

        alt7=32;

        switch ( LA(1) )
        {
        case '&':
        	{
        		alt7=1;
        	}
            break;
        case '(':
        	{
        		alt7=2;
        	}
            break;
        case ')':
        	{
        		alt7=3;
        	}
            break;
        case ',':
        	{
        		alt7=4;
        	}
            break;
        case ';':
        	{
        		alt7=5;
        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'a':
        					{
        						switch ( LA(4) )
        						{
        						case 'r':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt7=16;
        									}
        								    break;

        								default:
        								    alt7=6;
        								}

        							}
        						    break;

        						default:
        						    alt7=16;
        						}

        					}
        				    break;

        				default:
        				    alt7=16;
        				}

        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case 'e':
        	{
        		switch ( LA(2) )
        		{
        		case 'l':
        			{
        				switch ( LA(3) )
        				{
        				case 's':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt7=16;
        									}
        								    break;

        								default:
        								    alt7=7;
        								}

        							}
        						    break;

        						default:
        						    alt7=16;
        						}

        					}
        				    break;

        				default:
        				    alt7=16;
        				}

        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'f':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        				case '8':
        				case '9':
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case '_':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt7=16;
        					}
        				    break;

        				default:
        				    alt7=8;
        				}

        			}
        		    break;
        		case 'n':
        			{
        				switch ( LA(3) )
        				{
        				case 't':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt7=16;
        							}
        						    break;

        						default:
        						    alt7=9;
        						}

        					}
        				    break;

        				default:
        				    alt7=16;
        				}

        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case 'r':
        	{
        		switch ( LA(2) )
        		{
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 't':
        					{
        						switch ( LA(4) )
        						{
        						case 'u':
        							{
        								switch ( LA(5) )
        								{
        								case 'r':
        									{
        										switch ( LA(6) )
        										{
        										case 'n':
        											{
        												switch ( LA(7) )
        												{
        												case '0':
        												case '1':
        												case '2':
        												case '3':
        												case '4':
        												case '5':
        												case '6':
        												case '7':
        												case '8':
        												case '9':
        												case 'A':
        												case 'B':
        												case 'C':
        												case 'D':
        												case 'E':
        												case 'F':
        												case 'G':
        												case 'H':
        												case 'I':
        												case 'J':
        												case 'K':
        												case 'L':
        												case 'M':
        												case 'N':
        												case 'O':
        												case 'P':
        												case 'Q':
        												case 'R':
        												case 'S':
        												case 'T':
        												case 'U':
        												case 'V':
        												case 'W':
        												case 'X':
        												case 'Y':
        												case 'Z':
        												case '_':
        												case 'a':
        												case 'b':
        												case 'c':
        												case 'd':
        												case 'e':
        												case 'f':
        												case 'g':
        												case 'h':
        												case 'i':
        												case 'j':
        												case 'k':
        												case 'l':
        												case 'm':
        												case 'n':
        												case 'o':
        												case 'p':
        												case 'q':
        												case 'r':
        												case 's':
        												case 't':
        												case 'u':
        												case 'v':
        												case 'w':
        												case 'x':
        												case 'y':
        												case 'z':
        													{
        														alt7=16;
        													}
        												    break;

        												default:
        												    alt7=10;
        												}

        											}
        										    break;

        										default:
        										    alt7=16;
        										}

        									}
        								    break;

        								default:
        								    alt7=16;
        								}

        							}
        						    break;

        						default:
        						    alt7=16;
        						}

        					}
        				    break;

        				default:
        				    alt7=16;
        				}

        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case 'w':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'l':
        							{
        								switch ( LA(5) )
        								{
        								case 'e':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt7=16;
        											}
        										    break;

        										default:
        										    alt7=11;
        										}

        									}
        								    break;

        								default:
        								    alt7=16;
        								}

        							}
        						    break;

        						default:
        						    alt7=16;
        						}

        					}
        				    break;

        				default:
        				    alt7=16;
        				}

        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case '{':
        	{
        		alt7=12;
        	}
            break;
        case '}':
        	{
        		alt7=13;
        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt7=16;
        							}
        						    break;

        						default:
        						    alt7=14;
        						}

        					}
        				    break;

        				default:
        				    alt7=16;
        				}

        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case 'v':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'd':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt7=16;
        									}
        								    break;

        								default:
        								    alt7=15;
        								}

        							}
        						    break;

        						default:
        						    alt7=16;
        						}

        					}
        				    break;

        				default:
        				    alt7=16;
        				}

        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'd':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 's':
        case 't':
        case 'u':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt7=16;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt7=17;
        	}
            break;
        case '\'':
        	{
        		alt7=18;
        	}
            break;
        case '"':
        	{
        		alt7=19;
        	}
            break;
        case '=':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=21;
        			}
        		    break;

        		default:
        		    alt7=20;
        		}

        	}
            break;
        case '!':
        	{
        		alt7=22;
        	}
            break;
        case '<':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=24;
        			}
        		    break;

        		default:
        		    alt7=23;
        		}

        	}
            break;
        case '>':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=26;
        			}
        		    break;

        		default:
        		    alt7=25;
        		}

        	}
            break;
        case '+':
        	{
        		alt7=27;
        	}
            break;
        case '-':
        	{
        		alt7=28;
        	}
            break;
        case '/':
        	{
        		alt7=29;
        	}
            break;
        case '%':
        	{
        		alt7=30;
        	}
            break;
        case '*':
        	{
        		alt7=31;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt7=32;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 7;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt7)
        {
    	case 1:
    	    // SimpleC.g:1:10: T__39
    	    {
    	        /* 1:10: T__39 */
    	        mT__39(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // SimpleC.g:1:16: T__40
    	    {
    	        /* 1:16: T__40 */
    	        mT__40(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // SimpleC.g:1:22: T__41
    	    {
    	        /* 1:22: T__41 */
    	        mT__41(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // SimpleC.g:1:28: T__42
    	    {
    	        /* 1:28: T__42 */
    	        mT__42(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // SimpleC.g:1:34: T__43
    	    {
    	        /* 1:34: T__43 */
    	        mT__43(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // SimpleC.g:1:40: T__44
    	    {
    	        /* 1:40: T__44 */
    	        mT__44(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // SimpleC.g:1:46: T__45
    	    {
    	        /* 1:46: T__45 */
    	        mT__45(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // SimpleC.g:1:52: T__46
    	    {
    	        /* 1:52: T__46 */
    	        mT__46(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // SimpleC.g:1:58: T__47
    	    {
    	        /* 1:58: T__47 */
    	        mT__47(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // SimpleC.g:1:64: T__48
    	    {
    	        /* 1:64: T__48 */
    	        mT__48(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // SimpleC.g:1:70: T__49
    	    {
    	        /* 1:70: T__49 */
    	        mT__49(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // SimpleC.g:1:76: T__50
    	    {
    	        /* 1:76: T__50 */
    	        mT__50(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // SimpleC.g:1:82: T__51
    	    {
    	        /* 1:82: T__51 */
    	        mT__51(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // SimpleC.g:1:88: FOR
    	    {
    	        /* 1:88: FOR */
    	        mFOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // SimpleC.g:1:92: VOID_TYPE
    	    {
    	        /* 1:92: VOID_TYPE */
    	        mVOID_TYPE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // SimpleC.g:1:102: ID
    	    {
    	        /* 1:102: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // SimpleC.g:1:105: INT
    	    {
    	        /* 1:105: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // SimpleC.g:1:109: CHARACTER_LITERAL
    	    {
    	        /* 1:109: CHARACTER_LITERAL */
    	        mCHARACTER_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // SimpleC.g:1:127: STRING_LITERAL
    	    {
    	        /* 1:127: STRING_LITERAL */
    	        mSTRING_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // SimpleC.g:1:142: EQ
    	    {
    	        /* 1:142: EQ */
    	        mEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // SimpleC.g:1:145: EQEQ
    	    {
    	        /* 1:145: EQEQ */
    	        mEQEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // SimpleC.g:1:150: NEQ
    	    {
    	        /* 1:150: NEQ */
    	        mNEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // SimpleC.g:1:154: OPLT
    	    {
    	        /* 1:154: OPLT */
    	        mOPLT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // SimpleC.g:1:159: LTEQ
    	    {
    	        /* 1:159: LTEQ */
    	        mLTEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // SimpleC.g:1:164: OPGT
    	    {
    	        /* 1:164: OPGT */
    	        mOPGT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // SimpleC.g:1:169: GTEQ
    	    {
    	        /* 1:169: GTEQ */
    	        mGTEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // SimpleC.g:1:174: PLUS
    	    {
    	        /* 1:174: PLUS */
    	        mPLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // SimpleC.g:1:179: MINUS
    	    {
    	        /* 1:179: MINUS */
    	        mMINUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // SimpleC.g:1:185: DIVI
    	    {
    	        /* 1:185: DIVI */
    	        mDIVI(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // SimpleC.g:1:190: REST
    	    {
    	        /* 1:190: REST */
    	        mREST(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // SimpleC.g:1:195: MULT
    	    {
    	        /* 1:195: MULT */
    	        mMULT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // SimpleC.g:1:200: WS
    	    {
    	        /* 1:200: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
